"""
Medic — Self-Healing Health Monitoring Sub-Loop

The medic is the system's self-maintenance intelligence.

Its role:
- Inspect whether the rest of the organism is functioning
- Detect degradation before it becomes user-visible failure
- Attempt bounded recovery where possible
- Escalate clearly where autonomous repair is insufficient

The medic is NOT optional. It is part of what makes a persistent
deployment operationally credible.

A system that cannot inspect and recover itself is only
temporarily persistent.
"""

import asyncio
import logging
from typing import Dict, List, Any, Optional
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from enum import Enum


logger = logging.getLogger(__name__)


class HealthStatus(Enum):
    """Health status for monitored components."""
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    FAILED = "failed"
    UNKNOWN = "unknown"


@dataclass
class ComponentHealth:
    """Health status of a system component."""
    component: str
    status: HealthStatus
    last_check: datetime
    last_healthy: Optional[datetime] = None
    failure_count: int = 0
    last_failure_reason: Optional[str] = None
    recovery_attempted: bool = False
    recovery_successful: Optional[bool] = None


@dataclass
class MedicReport:
    """Report generated by medic cycle."""
    cycle_id: str
    started_at: datetime
    completed_at: datetime

    # Component health
    components_checked: int = 0
    components_healthy: int = 0
    components_degraded: int = 0
    components_failed: int = 0

    # Recovery actions
    recoveries_attempted: int = 0
    recoveries_successful: int = 0
    recoveries_failed: int = 0

    # Escalations
    escalations: List[Dict[str, Any]] = field(default_factory=list)

    # Details
    component_statuses: Dict[str, ComponentHealth] = field(default_factory=dict)
    issues_found: List[str] = field(default_factory=list)
    actions_taken: List[str] = field(default_factory=list)

    # Overall health
    system_healthy: bool = True


class Medic:
    """
    Self-healing health monitoring sub-loop.

    The medic runs on a schedule and performs systematic checks
    of the entire organism.
    """

    def __init__(
        self,
        state_manager: Any,
        config: Dict[str, Any],
        gateway: Optional[Any] = None
    ):
        self.state_manager = state_manager
        self.config = config
        self.gateway = gateway  # For escalation alerts

        # Component tracking
        self.component_health: Dict[str, ComponentHealth] = {}

        # Last medic run
        self.last_run: Optional[datetime] = None
        self.last_report: Optional[MedicReport] = None

        # Failure thresholds
        self.max_failures_before_escalation = config.get("medic", {}).get("max_failures", 3)
        self.health_check_window_hours = config.get("medic", {}).get("check_window_hours", 1)

        logger.info("Medic initialized")

    async def run_cycle(self) -> MedicReport:
        """
        Run a complete medic cycle.

        This is the systematic health inspection of the organism.
        """
        cycle_id = f"medic_{datetime.utcnow().timestamp()}"
        started_at = datetime.utcnow()

        logger.info(f"Starting medic cycle: {cycle_id}")

        report = MedicReport(
            cycle_id=cycle_id,
            started_at=started_at,
            completed_at=started_at  # Will update at end
        )

        try:
            # 1. Check runtime continuity
            await self._check_runtime_continuity(report)

            # 2. Check tool health
            await self._check_tool_health(report)

            # 3. Check memory freshness
            await self._check_memory_freshness(report)

            # 4. Check queue states
            await self._check_queue_states(report)

            # 5. Check integration availability
            await self._check_integration_health(report)

            # 6. Check schedule recency
            await self._check_schedule_recency(report)

            # 7. Check The Nine integrity
            await self._check_the_nine_integrity(report)

            # 8. Attempt recoveries
            await self._attempt_recoveries(report)

            # 9. Escalate critical issues
            await self._escalate_critical_issues(report)

        except Exception as e:
            logger.exception(f"Medic cycle {cycle_id} encountered error")
            report.issues_found.append(f"Medic cycle error: {str(e)}")
            report.system_healthy = False

        # Complete report
        report.completed_at = datetime.utcnow()

        # Calculate summary stats
        report.components_checked = len(report.component_statuses)
        for health in report.component_statuses.values():
            if health.status == HealthStatus.HEALTHY:
                report.components_healthy += 1
            elif health.status == HealthStatus.DEGRADED:
                report.components_degraded += 1
            elif health.status == HealthStatus.FAILED:
                report.components_failed += 1

        # Determine overall health
        if report.components_failed > 0:
            report.system_healthy = False
        elif report.components_degraded > 2:
            report.system_healthy = False

        # Update tracking
        self.last_run = datetime.utcnow()
        self.last_report = report

        logger.info(f"Medic cycle {cycle_id} complete: "
                   f"{report.components_healthy}/{report.components_checked} healthy, "
                   f"{report.recoveries_successful}/{report.recoveries_attempted} recoveries successful")

        return report

    async def _check_runtime_continuity(self, report: MedicReport):
        """Check if runtime is maintaining continuity."""
        component = "runtime_continuity"

        try:
            # Check if master loop state exists and is recent
            master_state = await self.state_manager.load_master_state("company-loop")

            if not master_state:
                health = ComponentHealth(
                    component=component,
                    status=HealthStatus.FAILED,
                    last_check=datetime.utcnow(),
                    last_failure_reason="No master loop state found"
                )
                report.issues_found.append("Runtime continuity lost - no master state")
            else:
                # Check recency
                last_session = master_state.get("last_session")
                if last_session:
                    last_session_dt = datetime.fromisoformat(last_session)
                    age_hours = (datetime.utcnow() - last_session_dt).total_seconds() / 3600

                    if age_hours > self.health_check_window_hours:
                        health = ComponentHealth(
                            component=component,
                            status=HealthStatus.DEGRADED,
                            last_check=datetime.utcnow(),
                            last_failure_reason=f"Master state stale ({age_hours:.1f} hours old)"
                        )
                        report.issues_found.append(f"Runtime continuity degraded - state {age_hours:.1f}h old")
                    else:
                        health = ComponentHealth(
                            component=component,
                            status=HealthStatus.HEALTHY,
                            last_check=datetime.utcnow(),
                            last_healthy=datetime.utcnow()
                        )
                else:
                    health = ComponentHealth(
                        component=component,
                        status=HealthStatus.DEGRADED,
                        last_check=datetime.utcnow(),
                        last_failure_reason="No last_session timestamp in state"
                    )

            report.component_statuses[component] = health
            self.component_health[component] = health

        except Exception as e:
            logger.exception(f"Error checking {component}")
            health = ComponentHealth(
                component=component,
                status=HealthStatus.FAILED,
                last_check=datetime.utcnow(),
                last_failure_reason=str(e)
            )
            report.component_statuses[component] = health
            report.issues_found.append(f"{component} check failed: {str(e)}")

    async def _check_tool_health(self, report: MedicReport):
        """Check health of tool integrations."""
        # Placeholder - would check VY, integrations, etc.
        component = "tool_health"

        # For now, mark as healthy
        health = ComponentHealth(
            component=component,
            status=HealthStatus.HEALTHY,
            last_check=datetime.utcnow(),
            last_healthy=datetime.utcnow()
        )
        report.component_statuses[component] = health

    async def _check_memory_freshness(self, report: MedicReport):
        """Check if memory systems are current."""
        component = "memory_freshness"

        try:
            # Check if working memory exists
            # In real implementation, would check The Nine files

            health = ComponentHealth(
                component=component,
                status=HealthStatus.HEALTHY,
                last_check=datetime.utcnow(),
                last_healthy=datetime.utcnow()
            )
            report.component_statuses[component] = health

        except Exception as e:
            logger.exception(f"Error checking {component}")
            health = ComponentHealth(
                component=component,
                status=HealthStatus.FAILED,
                last_check=datetime.utcnow(),
                last_failure_reason=str(e)
            )
            report.component_statuses[component] = health
            report.issues_found.append(f"Memory freshness check failed: {str(e)}")

    async def _check_queue_states(self, report: MedicReport):
        """Check if task queues are healthy."""
        component = "queue_health"

        # Placeholder - would check Linear, Symphony queues
        health = ComponentHealth(
            component=component,
            status=HealthStatus.HEALTHY,
            last_check=datetime.utcnow(),
            last_healthy=datetime.utcnow()
        )
        report.component_statuses[component] = health

    async def _check_integration_health(self, report: MedicReport):
        """Check if external integrations are reachable."""
        # Placeholder - would check Google, ClickUp, Close, etc.
        component = "integration_health"

        health = ComponentHealth(
            component=component,
            status=HealthStatus.HEALTHY,
            last_check=datetime.utcnow(),
            last_healthy=datetime.utcnow()
        )
        report.component_statuses[component] = health

    async def _check_schedule_recency(self, report: MedicReport):
        """Check if scheduled jobs are running on time."""
        component = "schedule_recency"

        # Placeholder - would check cron execution
        health = ComponentHealth(
            component=component,
            status=HealthStatus.HEALTHY,
            last_check=datetime.utcnow(),
            last_healthy=datetime.utcnow()
        )
        report.component_statuses[component] = health

    async def _check_the_nine_integrity(self, report: MedicReport):
        """Check if The Nine files are present and valid."""
        component = "the_nine_integrity"

        # Placeholder - would check all Nine files
        health = ComponentHealth(
            component=component,
            status=HealthStatus.HEALTHY,
            last_check=datetime.utcnow(),
            last_healthy=datetime.utcnow()
        )
        report.component_statuses[component] = health

    async def _attempt_recoveries(self, report: MedicReport):
        """Attempt automatic recovery for failed/degraded components."""
        for component_name, health in report.component_statuses.items():
            if health.status in [HealthStatus.FAILED, HealthStatus.DEGRADED]:
                # Attempt recovery based on component type
                recovery_result = await self._recover_component(component_name, health)

                if recovery_result["attempted"]:
                    report.recoveries_attempted += 1
                    health.recovery_attempted = True

                    if recovery_result["successful"]:
                        report.recoveries_successful += 1
                        health.recovery_successful = True
                        health.status = HealthStatus.HEALTHY
                        health.last_healthy = datetime.utcnow()
                        health.failure_count = 0
                        report.actions_taken.append(f"Recovered {component_name}: {recovery_result['action']}")
                    else:
                        report.recoveries_failed += 1
                        health.recovery_successful = False
                        health.failure_count += 1
                        report.actions_taken.append(f"Failed to recover {component_name}: {recovery_result['reason']}")

    async def _recover_component(self, component: str, health: ComponentHealth) -> Dict[str, Any]:
        """
        Attempt bounded recovery for a component.

        Returns dict with: attempted, successful, action, reason
        """
        logger.info(f"Attempting recovery for {component}")

        # Recovery strategies by component type
        if component == "runtime_continuity":
            # Could try: reinitialize state, reload config, etc.
            return {
                "attempted": True,
                "successful": False,
                "action": "state_reinit",
                "reason": "Auto-recovery not yet implemented"
            }

        # Default: no recovery available
        return {
            "attempted": False,
            "successful": False,
            "action": None,
            "reason": "No recovery strategy defined"
        }

    async def _escalate_critical_issues(self, report: MedicReport):
        """Escalate critical issues that require human attention."""
        critical_components = [
            name for name, health in report.component_statuses.items()
            if health.status == HealthStatus.FAILED and health.failure_count >= self.max_failures_before_escalation
        ]

        if critical_components:
            escalation = {
                "timestamp": datetime.utcnow().isoformat(),
                "severity": "critical",
                "components": critical_components,
                "message": f"Critical system failures in: {', '.join(critical_components)}",
                "report_id": report.cycle_id
            }

            report.escalations.append(escalation)

            # Send alert through gateway if available
            if self.gateway:
                await self.gateway.send_alert(
                    severity="critical",
                    message=escalation["message"],
                    details=escalation
                )

            logger.critical(f"Escalating critical issues: {critical_components}")

    async def get_health_summary(self) -> Dict[str, Any]:
        """Get current health summary."""
        if not self.last_report:
            return {
                "status": "unknown",
                "message": "No medic report available yet"
            }

        return {
            "status": "healthy" if self.last_report.system_healthy else "unhealthy",
            "last_check": self.last_run.isoformat() if self.last_run else None,
            "components_healthy": self.last_report.components_healthy,
            "components_degraded": self.last_report.components_degraded,
            "components_failed": self.last_report.components_failed,
            "issues": self.last_report.issues_found,
            "escalations": len(self.last_report.escalations)
        }
